<?php
$page_title = 'Report History';
require_once('includes/load.php');
// Check if the user has permission
page_require_level(1);

// Set records per page
$records_per_page = 9;

// Get current page or set default
$current_page = isset($_GET['page']) ? (int)$_GET['page'] : 1;

// Calculate the offset for the query
$offset = ($current_page - 1) * $records_per_page;

// Fetch the report history from the database with pagination
$report_history = fetch_report_history_paginated($offset, $records_per_page);

// Count total records for pagination
$total_records = count_report_history();

// Calculate total pages
$total_pages = ceil($total_records / $records_per_page);
?>

<?php include_once('layouts/header.php'); ?>

<div class="row">
    <div class="col-12">
        <div class="card shadow-sm border-0">
            <div class="card-header cont-head d-flex align-items-center">
                <i class="bi bi-clock-history me-2 symbol"></i>
                <h5 class="mb-0">Report History</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover align-middle">
                        <thead class="table-light">
                            <tr>
                                <th scope="col">Report ID</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Location</th>
                                <th scope="col">Report Type</th>
                                <th scope="col">Date Generated</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($report_history as $report): ?>
                                <tr>
                                    <td><?= count_id(); ?></td>
                                    <td><?php echo get_user_by_id($report['generated_by'])['username']; ?></td>
                                    <td><?php echo get_location_name($report['location_id']); ?></td>
                                    <td><?php echo $report['report_type']; ?></td>
                                    <td><?php echo date('Y-m-d H:i:s', strtotime($report['generated_at'])); ?></td>
                                    <td>
                                        <?php if (!empty($report['file_path'])): ?>
                                            <a href="<?php echo $report['file_path']; ?>" class="btn secondary-btn btn-sm">
                                                <i class="bi bi-download"></i> Download
                                            </a>
                                        <?php else: ?>
                                            <span class="text-muted">N/A</span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            <?php if (empty($report_history)): ?>
                                <tr>
                                    <td colspan="6" class="text-center text-muted">No reports available.</td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
                
                <!-- Pagination -->
                <?php if ($total_pages > 1): ?>
                <nav aria-label="Page navigation" class="mt-4">
                    <ul class="pagination justify-content-center">
                        <!-- Previous button -->
                        <li class="page-item <?php echo ($current_page <= 1) ? 'disabled' : ''; ?>">
                            <a class="page-link" href="?page=<?php echo $current_page - 1; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        
                        <!-- Page numbers -->
                        <?php
                        // Define how many page numbers to show
                        $max_links = 5;
                        $start_page = max(1, $current_page - floor($max_links / 2));
                        $end_page = min($total_pages, $start_page + $max_links - 1);
                        
                        // Adjust start page if needed
                        if ($end_page - $start_page + 1 < $max_links) {
                            $start_page = max(1, $end_page - $max_links + 1);
                        }
                        
                        // First page link if not in range
                        if ($start_page > 1): ?>
                            <li class="page-item">
                                <a class="page-link" href="?page=1">1</a>
                            </li>
                            <?php if ($start_page > 2): ?>
                                <li class="page-item disabled"><a class="page-link">...</a></li>
                            <?php endif; 
                        endif;
                        
                        // Page numbers
                        for ($i = $start_page; $i <= $end_page; $i++): ?>
                            <li class="page-item <?php echo ($i == $current_page) ? 'active' : ''; ?>">
                                <a class="page-link" href="?page=<?php echo $i; ?>"><?php echo $i; ?></a>
                            </li>
                        <?php endfor;
                        
                        // Last page link if not in range
                        if ($end_page < $total_pages): 
                            if ($end_page < $total_pages - 1): ?>
                                <li class="page-item disabled"><a class="page-link">...</a></li>
                            <?php endif; ?>
                            <li class="page-item">
                                <a class="page-link" href="?page=<?php echo $total_pages; ?>"><?php echo $total_pages; ?></a>
                            </li>
                        <?php endif; ?>
                        
                        <!-- Next button -->
                        <li class="page-item <?php echo ($current_page >= $total_pages) ? 'disabled' : ''; ?>">
                            <a class="page-link" href="?page=<?php echo $current_page + 1; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <?php endif; ?>
                
                <!-- Page info -->
                <div class="text-center mt-2">
                    <span class="text-muted">Showing <?php echo ($offset + 1); ?> to <?php echo min($offset + $records_per_page, $total_records); ?> of <?php echo $total_records; ?> reports</span>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include_once('layouts/footer.php'); ?>